### ISSUE TITLE
Please add letsencrypt support to ini

### ISSUE THREAD

**Issue by 1xPdd** [YunoHost-Apps/mumbleserver_ynh#8]
Hi. Thanks for bringing Mumble to Yunohost!

Now that Yunohost 2.5 supports Let's Encrypt, it would be great if the mumble-server.ini file used the crt.pem and key.pem files, which, I believe, are in /etc/yunohost/certs/[domainname].

Cheers!

**Comment by M5oul** [comment]
### Todo
- [x] Wait stable release of YunoHost 2.6.
- [ ] Set `yunohost >= 2.6.3` as dependency on the manifest to have [permissions on certificates](https://github.com/YunoHost/yunohost/pull/222).
- [ ] Modify [certificate lines on `mumble-server.ini`](https://github.com/YunoHost-Apps/mumbleserver_ynh/blob/master/conf/mumble-server.ini#L158-L161).
- [ ] add `mumble-server` user to `ssl-cert` group: `usermod -G ssl-cert mumble-server`.

---
### Could be done later
- [Live Reloading of Certificates](https://wiki.mumble.info/wiki/Obtaining_a_Let's_Encrypt_Murmur_Certificate).

**Comment by 1xPdd** [comment]
Great, thanks!

**Comment by Jibec** [comment]
Fixed by https://github.com/YunoHost-Apps/mumbleserver_ynh/commit/691b1abb774c7b927db4aced766d2e3099a2313a
